### ISSUE TITLE
Additional column 'warning' in correlation_matrix

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog_corr#4]
@mmaelicke, what do you think about an additional column `warning` in the correlation_matrix table, where we insert the warnings returned by the metric functions?
Many of these functions generate warnings if, for example, the input data is not compatible with the calculation of the metric or if errors occur during the calculation.

Examples:
```
SpearmanRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(SpearmanRConstantInputWarning())

RuntimeWarning: invalid value encountered in true_divide
  P = (X - M) / omega
```

This way it would be traceable why a function returns NaN or if there could be problems with the data or a function.

**Comment by mmaelicke** [comment]
I will put my answer into #5
